config/routes.rb
Rails.application.routes.draw do
	
	get '/login', to: 'sessions#new'
	
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  get '/', to: 'sessions#new'

  get '/expense_index', to: 'travel_plans#expense_index'

  get '/index', to: 'users#index'

  get '/category/total_report', to: 'categories#total_report'

  resources :travel_plan_entries, :travel_plans, :users

  resources :travel_plans do 
  	resources :categories 
  end

  resources :travel_plans do 
    resources :travel_plan_entries
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :subcategory
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
	belongs_to :category
end

app/models/travel_plan.rb
class TravelPlan < ActiveRecord::Base
	belongs_to :user
	has_many :travel_plan_entry
	has_many :category
end

app/models/travel_plan_entry.rb
class TravelPlanEntry < ActiveRecord::Base
	belongs_to :travel_plan
	has_one :subcategory
	has_one :category

	 has_attached_file :expense_file, styles: {
    medium: '300x300>',
    thumb: '100x100>'  
  }, :default_url => ""
	# Validate the attached image is image/jpg, image/png, etc
  	validates_attachment_content_type :expense_file, :content_type => /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :travel_plan
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def total_report
		@plan = TravelPlan.find(params[:id])
		@entries = @plan.travel_plan_entry 
		 @amount = @entries.group('category_id').sum('estimated_amount')
		 @expense = @entries.group('category_id').sum('actual_expense')
		 @total_estimated = @plan.travel_plan_entry.sum('estimated_amount')
		@total_expense = @plan.travel_plan_entry.sum('actual_expense')
		 @categories = Category.all 
			render partial: 'total_category'
	end

	def show
		@category = Category.find(params[:id])
		plan_id = params[:travel_plan_id]
		@plan = TravelPlan.find(plan_id)
		@total_estimated = @plan.travel_plan_entry.sum('estimated_amount')
		@total_expense = @plan.travel_plan_entry.sum('actual_expense')
		@entries = []
		@category.subcategory.each do |sub|
			entry = TravelPlanEntry.where(travel_plan_id: plan_id, subcategory_id: sub.id)
			if (entry != [])&&(entry != nil)
				@entries.push(entry)
			end
		end
		
		render partial: 'show_category'
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	#renders the login form
  def new 
  end

  #creates a session
  def create
    user = User.find_by({user_name: params[:user_name]})
    if user && user.authenticate(params[:password])    
      session[:user_id] = user.id
      session[:user_name] = user.user_name
      session[:user_fullname] = "#{user.f_name} #{user.l_name}"
      redirect_to "/index" #user index page
    else
      # rerender the form
      redirect_to '/login'
    end
  end

  #nulls user session (logout)
  def destroy
  	session[:user_id] = nil
    session[:user_name] = nil
  	redirect_to '/login'
  end

end

app/controllers/travel_plan_entries_controller.rb
class TravelPlanEntriesController < ApplicationController
	def update
		@entry = TravelPlanEntry.find(params[:id])
		@entry.update(travel_plan_entry_params)
		plan_id = @entry.travel_plan_id
		redirect_to "/travel_plans/#{plan_id}/edit"
	end

	def edit 
		@entry = TravelPlanEntry.find(params[:id])
	end

	def show
		@entry = TravelPlanEntry.find(params[:id])
		@travelplan = TravelPlan.find(params[:travel_plan_id])
	end

	private

	def travel_plan_entry_params
		params.require(:travel_plan_entry).permit(
			:travel_plan_id,
			:notes,
			:expense_file,
			:actual_expense,
			:estimated_amount)
	end
end

app/controllers/travel_plans_controller.rb
class TravelPlansController < ApplicationController

	def current_user 
		@user = User.find(session[:user_id])
	end

	def index
		@user = User.find(current_user.id)
		@travelplans = TravelPlan.where(user_id: @user.id)
	end

	def show
		@user = User.find(current_user)
		@travelplan = TravelPlan.find(params[:id])
		@categories = Category.all 
	end

	def new 
		@categories = Category.all
		@travelplan = TravelPlan.new
	end

	def create
		@categories = Category.all
		@travelplan = TravelPlan.new(travel_plan_params)
		@travelplan.user_id = current_user.id
		@travelplan.save
		# associate travelplaneentries with the subcategories
		params["subcategories"].each do |sub|
			cat = Subcategory.find(sub).category_id
			TravelPlanEntry.create({
				travel_plan_id: @travelplan.id, subcategory_id: sub,
					category_id: cat
			})	
		end
		redirect_to "/travel_plans/#{@travelplan.id}/edit"
	end

	def edit 
		@travelplan = TravelPlan.find(params[:id])
		@user = current_user
		@entries = @travelplan.travel_plan_entry
	end

	def update
	end

	def destroy
	end

	def expense_index
		@user = User.find(current_user.id)
		@travelplans = TravelPlan.where(user_id: @user.id)
		
		render 'upload_expense_index'
	end

	def upload
  uploaded_io = params[:user][:expense_file]
	  File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
	    file.write(uploaded_io.read)
	  end
	end

	private

	def travel_plan_params
		params.require(:travel_plan).permit(
			:is_international,
			:destination_city,
			:destination_country,
			:departure_city,
			:departure_country,
			:user_id,
			:start_date,
			:end_date)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def current_user 
		@user = User.find(session[:user_id])
	end

	# --- index is dashboard page. user needs log in to see the page --- 
	def index
		@user = current_user
	end

	# ---- this is route for profile page ---- #
	def show 
		@user = User.find(params[:id])
	end

	def new 
		@user = User.new
	end

	# ---- new user sign in page --- # 
	def create
		user = User.new
		@user = user.update(user_params)
		redirect_to '/login'
	end

	  private

  def user_params
    params.permit(:user_name, :user_email, :password, :password_confirmation, :f_name, :l_name, :user_profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/travel_expense_entries_helper.rb
module TravelExpenseEntriesHelper
end

app/helpers/travel_plan_entries_helper.rb
module TravelPlanEntriesHelper
end

app/helpers/travel_plans_helper.rb
module TravelPlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_show_category.html.erb
<div class="panel panel-success">
<h1 class="panel-heading"><%= @category.category_name.capitalize %></h1>
	<div> 
		Total Estimated: <%= @total_estimated %>
	</div>
	<div> 
		Total Expenses: <%= @total_expense %>
	</div>

	<h3> Details: </h3><br>
	<table class="table table-striped">
		<caption></caption>
		<thead>
			<tr>
				<th>category</th>
				<th>notes</th>
				<th>estimated amt</th>
				<th>actual expense</th>
				<th>created</th>
				<th>updated</th>
			</tr>
		</thead>
				<tbody>
				<% @entries.each do |entry| %>
					<tr>
						<td><%= Subcategory.find(entry[0].subcategory_id).subcategory_name %></td>
						<td><%= entry[0].notes %></td>
						<td><%= entry[0].estimated_amount %></td>
						<td><%= entry[0].actual_expense %></td>
						<td><%= entry[0].created_at.to_date %></td>
						<td><%= entry[0].updated_at.to_date %></td>
					</tr>
				</tbody>
				<% end %>
</div>

app/views/categories/_total_category.html.erb
<div class="panel panel-success">
<h1 class="panel-heading">Total</h1>
	<div> 
		Total Estimated: <%= @total_estimated %>
	</div>
	<div> 
		Total Expenses: <%= @total_expense %>
	</div>

	<h3> Details: </h3><br>
	<table class="table table-striped">
		<caption></caption>
		<thead>
			<tr>
				<th>category</th>
				<th>estimated amt</th>
				<th>actual expense</th>
			</tr>
		</thead>
				<tbody>
				<% @categories.each do |cat| %>
					<tr>
						<td><%= cat.category_name %></td>
						<td><%= @amount[cat.id] %></td>
						<td><%= @expense[cat.id] %></td>
					</tr>
				</tbody>
				<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelPlanner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id='yield-page'>
		<%= link_to 'Go to Homepage', '/index' %>
		<%= yield %>
	</div>
</body>
</html>

app/views/travel_plan_entries/edit.html.erb
				
<br><br>
<div class="panel panel-success">
<h1 class="panel-heading"> Receipt Upload Page </h1>
	<div class= "panel-body" id="entry-expense-file"><%= form_for @entry, :url => "/travel_plan_entries/#{@entry.id}", :html => { :multipart => true } do |form| %> <%= form.file_field :expense_file, :class => 'col-md-6' %><br><br>
					<%= form.submit 'upload file', :class => 'col-md-6' %><% end %>
	</div> 

app/views/travel_plan_entries/show.html.erb
<div><%= image_tag @entry.expense_file.url(:medium) %></div>
<%= button_to 'Back to List', "/travel_plans/" + @travelplan.id.to_s + "/edit", method: "get", class: "btn btn-primary btn-md" %>

app/views/travel_plans/edit.html.erb
<h1 class="travel-plan-edit">Travel Plan Edit Page</h1>

<% if  @travelplan.is_international == false %>
	<h3>Type: <%= "Domestic Trip" %></h3>

<% elsif @travelplan.is_international == true %>
	<h3>Type: <%= "International" %></h3>
<% end %>
	<h3>Departure: <%= @travelplan.departure_city %> , <%= @travelplan.departure_country %></h3>
	<h3>Destination: <%= @travelplan.destination_city %> , <%= @travelplan.destination_country %></h3>
	<h3>Date: <%= @travelplan.start_date.to_date %> ~ <%= @travelplan.end_date.to_date %></h3>

	<h3> Travel Plan Details: </h3><br>
	<table class="travel-plan-detail table table-striped">
		<caption></caption>
		<thead>
			<tr>
				<th>category</th>
				<th>notes</th>
				<th>estimated amt</th>
				<th>actual expense</th>
				<th>created</th>
				<th>updated</th>
				<th>edit entry</th>
				<th id="entry-expense-file">expense file</th>
			</tr>
		</thead>
		<tbody>
		<% @entries.each do |entry| %>
			<tr>
				<td><%= Subcategory.find(entry.subcategory_id).subcategory_name.capitalize %></td>
				<td><input type="text" id="entry-notes" value="<%= entry.notes %>"></input></td>
				<td><input type="text" id="entry-estimated-amount" value="<%= entry.estimated_amount %>"></input></td>
				<td><input type="text" id="entry-actual-expense" value="<%= entry.actual_expense %>"></input></td>
				<td><%= entry.created_at.to_date %></td>
				<td><%= entry.updated_at.to_date %></td>
				<td>
					<button class='travel-plan-page-update-button btn btn-primary btn-md' id='<%=entry.id%>'>update</button></td>
				<td><% if entry.expense_file_file_name != nil %>
					 		<%= link_to 'view receipt', "/travel_plans/" + @travelplan.id.to_s + "/travel_plan_entries/" + entry.id.to_s%><br>
					 	<% end %>
					 		<%= link_to 'attach file', "/travel_plan_entries/" + entry.id.to_s + "/edit"%>
				</td>
			</tr>
		</tbody><tr><tr><tr><tr><tr>
		<% end %>
	</table><br></br>

app/views/travel_plans/index.html.erb
<h1>Travel Plans for <%= @user.user_name.capitalize %></h1>
<% @travelplans.each do |travel_plan| %>
	<% travel_plan_name = travel_plan.destination_city + ', ' + travel_plan.destination_country  %>
	<li><%= link_to "#{travel_plan_name}", "travel_plans/#{travel_plan.id}" %></li>
<% end %>

app/views/travel_plans/new.html.erb
<h1>New Travel Plan</h1>

<div class="new-travel-plan-container">
	<form action="/travel_plans" method="post">
		<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
		<%# add options to each category #%>
		<select class="form-control" name="travel_plan[is_international]" id="select_trip_type">
				<option value="0">Select Trip Type</option>
				<option value="true">International</option>
				<option value="false">Domestic</option>
		</select><br><br>

		<%# travel-plan - dates #%>
		<label>Start-Date</label>
		<input type="date" name="travel_plan[start_date]"><br>
		<label>End-Date</label>
		<input type="date" name="travel_plan[end_date]"><br><br>

		<%# travel-plan - cities #%>
		<label>Departure-City</label>
		<input type="text" name="travel_plan[departure_city]"><br>
		<label>Departure-Country</label>
		<input type="text" name="travel_plan[departure_country]"><br><br>
		<label>Destination-City</label>
		<input type="text" name="travel_plan[destination_city]"><br>
		<label>Destination-Country</label>
		<input type="text" name="travel_plan[destination_country]"><br><br>

		<%# travel-plan - entries #%>
		<% @categories.each do |category| %>
			<% subcategories = category.subcategory %>
			<div class="panel panel-info category-<%= category.id %>">
			<h2 class="panel-heading"><%= category.category_name.capitalize %></h2>
				<% subcategories.each do |subcategory| %>
			 <div class="panel-body"><input type="checkbox" name="subcategories[]" value="<%= subcategory.id %>">
				<%= subcategory.subcategory_name.capitalize %><br></div>
			<% end %>
		<% end %>
		<br><br>

		<input class="btn btn-primary btn-lg" type="submit" value="Create Travel Plan"><br><br>
	</form>
</div>

app/views/travel_plans/show.html.erb
<%# navagation bar #%>
<h3 class="travel-show-page-title" id="<%=@travelplan.id%>" >Travel Plan Show Page</h3>


<div class = "navigation_bar">
	<div class = "show-category" id ="total"><button class="tab-class-button btn btn-primary btn-md btn-info">Total Tab</button></div>
<% @categories.each do |category| %>
	<div class = "show-category" id = "<%=category.id%>"> <button class="tab-class-button btn btn-primary btn-md btn-info"><%= category.category_name.capitalize %> Tab</button></div>
<% end %>
</div>
<div id="travel-plan-result-show"> 
	<div class = "travel-plan-container">
	</div>
</div>

app/views/travel_plans/travel_plans.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelPlanner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1> travel plans layout </h1>
<div class = "navigation_bar">
	<div> Total </div>
<% @categories.each do |category| %>
	<div> <%= category.category_name.capitalize %></div>
<% end %>
</div> 
<div class = "travel-plan-container">
<%= yield %>
</div>


</body>
</html>

app/views/users/index.html.erb
<img id="earth-image" src="http://i.imgur.com/GwUg64L.png"></img>
<br><br>
<h1> Travel Planner - TravelKit</h1>
<div class="sticky">
<div class="fixed">
  <nav class="navigation_container permanent-header top-bar">

  <div><button class='col-md-3 choice'><%= link_to "Profile", user_path(@user) %></button></div>
  <div><button class='col-md-3 choice'><%= link_to "Past Travel Analytics", travel_plans_path %></button></div>
  <div><button class='col-md-3 choice'><%= link_to "Create Travel Plan", new_travel_plan_path %></button></div>
  <div><button class='col-md-3 choice'><%= link_to "Upload Expense File", '/expense_index' %></button></div>
  </nav>
</div>
</div>
<br><br><br>
<div id="city-weather-search">
  <h5>Powered by Weather API</h5>
  <input class='col-md-6' type="text" id="city-search-text" placeholder="search by city name to get weather info  ex) 'London'"></input>
  <button class='btn btn-primary btn-sm' id="city-search-button">Search</button>
  <span id="result-cityname"></span><span id="result-temp"></span><span id="result-desc"></span>
</div>
<br><br>
<div id="country-currency-search">
  <h5>Powered by Openexchange API</h5>
  <input class='col-md-6' type="text" id="currency-search-text" placeholder="search by currency code to get exchange info  ex) 'KRW' for Korea"></input>
  <button class='btn btn-primary btn-sm' id="currency-search-button">Search</button>
  <span id="result-rate"></span><span id="result-exchange"></span>
</div>
<br>
<a href="http://www.science.co.il/International/Currency-codes.asp">link to currency code list</a>
<br><br>

<div id="carousel-picture-generic" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carousel-picture-generic" data-slide-to="0" class=""></li>
          <li data-target="#carousel-picture-generic" data-slide-to="1" class="active"></li>
          <li data-target="#carousel-picture-generic" data-slide-to="2" class=""></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <div class="item">
            <img class="carousel-pic" src="http://topwalls.net/wallpapers/2012/06/Arizona-Grand-Canyon-960x1280.jpg" data-holder-rendered="true">
          </div>
          <div class="item active">
            <img class="carousel-pic" src="http://www.mrwallpaper.com/wallpapers/Night-New-York-1280x960.jpg" data-holder-rendered="true">
          </div>
          <div class="item">
            <img class="carousel-pic" src="http://upload.wikimedia.org/wikipedia/commons/6/6a/MohonkHouse.jpg" data-holder-rendered="true">
          </div>
        </div>
        <a class="left carousel-control" href="#carousel-picture-generic" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        </a>
        <a class="right carousel-control" href="#carousel-picture-generic" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
</div>
<br>
<br>
<br>
<div id="youtube-">
  <iframe class="col-md-6" width="420" height="315" src="https://www.youtube.com/embed/xMfz1jlyQrw" frameborder="0"></iframe>

  <iframe class="col-md-6" width="420" height="315" src="https://www.youtube.com/embed/bch1_Ep5M1s" frameborder="0"></iframe>
</div>

app/views/users/new.html.erb
<h1> New User Sign Up Page </h1>
<h3> Please fill in all the required information </h3>

<%= form_tag users_path, method: 'post', :class => 'sign_up_form' do %>
					<%= label_tag :username %>:<br>
				  <%= text_field_tag :user_name %><br>
				  <%= label_tag :email %>:<br>
				  <%= text_field_tag :user_email %><br>
				  <%= label_tag :first_name %>:<br>
				  <%= text_field_tag :f_name %><br>
				  <%= label_tag :last_name %>:<br>
				  <%= text_field_tag :l_name %><br>
				  <%= label_tag :image_url %>:<br>
				  <%= text_field_tag :user_profile_image %><br>
				  <%= label_tag :password %>:<br>
				  <%= password_field_tag :password %><br>	
				  <%= label_tag :password_confirmation %>:<br>
				  <%= password_field_tag :password_confirmation %><br><br>
				  <%= submit_tag :confirm, :class => 'btn btn-primary btn-md' %><br><br>
<% end %>

app/views/users/show.html.erb
<h1>User Profile Page</h1>

<div id="profile-image-container">
	<img id="profile-page-image" class="img-thumbnail" src="<%= @user.user_profile_image %>"></img>
</div>
<div id="profile-information-container">
	<div>Username: <%= @user.user_name %> </div>
	<div>Email: <%= @user.user_email %></div>
	<div>Started Travel Planner on : <%= @user.created_at %> </div>
	<div>Number of Travels This Year: </div>
	<div>Upcoming Travel Destination: </div>
</div>